title: Wenting Luan
email: luanwenting20@163.com
description: >- 
  Personal website of Wenting Luan
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lwttttt.github.io" # the base hostname & protocol for your site
github_username: lwttttt

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
theme: minima

# Assets
sass:
  style: compressed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

#Update all the sections by editing the files inside _includes folder.
