title: Wenting Luan

#sidebar links
email: luanwenting20@163.com
website_github: Github
website_google: Google Scholar
port: 8000

# GitHub Pages settings
baseurl: ""
url: "https://lwttttt.github.io"
markdown: kramdown
theme: jekyll-theme-minimal

#Update all the sections by editing the files inside _includes folder.
