title: Your Name

#sidebar links
email: your.email@example.com
website_github: Github
#website_google: Google Scholar

# GitHub Pages settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lwttttt.github.io" # the base hostname & protocol for your site
github_username: lwttttt

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme settings
theme: minima

# Assets
sass:
  style: compressed

#Update all the sections by editing the files inside _includes folder.
