title: Wenting Luan

#sidebar links
email: luanwenting20@163.com
website_github: Github
website_google: Google Scholar

# GitHub Pages settings
baseurl: ""
url: "https://lwttttt.github.io"
markdown: kramdown
theme: minima

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - projects/

#Update all the sections by editing the files inside _includes folder.
